services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/template.tmpl:/etc/alertmanager/template.tmpl
    ports:
      - "9093:9093"
    restart: unless-stopped
    networks:
      - app_network
 
  postgres:
    image: postgres:14.17-alpine3.21
    container_name: PostgresDB
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5572:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s

  redis:
    image: redis:6-alpine
    container_name: Redis
    restart: always
    volumes:
      - .\redis\etc\redis.conf:/usr/local/etc/redis/redis.conf
      - .\redis\data:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "" > /usr/local/etc/redis/redis.conf &&
        echo "" > /usr/local/etc/redis/users.acl &&

        echo "bind 0.0.0.0" >> /usr/local/etc/redis/redis.conf &&
        echo "protected-mode no" >> /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo " loglevel notice" >> /usr/local/etc/redis/redis.conf &&
        echo "logfile /data/log/redis-server.log" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfilename "appendonly.aof"" >> /usr/local/etc/redis/redis.conf &&
        echo "auto-aof-rewrite-percentage 100" >> /usr/local/etc/redis/redis.conf &&
        echo "auto-aof-rewrite-min-size 64mb" >> /usr/local/etc/redis/redis.conf &&
        echo "maxmemory 256mb" >> /usr/local/etc/redis/redis.conf
        echo "maxmemory-policy allkeys-lru" >> /usr/local/etc/redis/redis.conf

        echo "user $BackEnd_USER on >$BackEnd_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        echo "user $Exporter_USER on >$Exporter_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BackEnd_USER: ${BackEnd_USER}
      BackEnd_USER_PASSWORD: ${BackEnd_USER_PASSWORD}
      Exporter_USER: ${Exporter_USER}
      Exporter_USER_PASSWORD: ${Exporter_USER_PASSWORD}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    environment:
      REDIS_ADDR: redis:6379
      REDIS_USER: ${Exporter_USER}
      REDIS_PASSWORD: ${Exporter_USER_PASSWORD}
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - app_network

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - app_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: App
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      - REDIS_URL=redis://${BackEnd_USER}:${BackEnd_USER_PASSWORD}@Redis:6379 
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
      - FRONTEND_URL=${FRONTEND_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - PASSWORD_RESET_CODE_EXPIRE_MINUTES=${PASSWORD_RESET_CODE_EXPIRE_MINUTES}
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - 8005:8005

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Frontend
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/Redis.yml:/etc/prometheus/Redis.yml 
      - ./prometheus/postgres.yml:/etc/prometheus/postgres.yml
      - ./prometheus/App.yml:/etc/prometheus/App.yml
      - ./prometheus/Frontend.yml:/etc/prometheus/Frontend.yml
      - prometheus_data:/prometheus
    ports:
      - "7090:9090"
    restart: unless-stopped
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "2222:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
  redis_data:
  prometheus_data:
  grafana_data: