services:
  postgres:
    image: postgres:17
    container_name: PostgresDB
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s

  redis:
    image: redis:7.4.2
    container_name: Redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: App
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
      - FRONTEND_URL=http://127.0.0.1:8085
    volumes:
      - ./backend:/app
    restart: unless-stopped
    entrypoint: >
      sh -c "pip install --no-cache-dir alembic asyncpg python-dotenv && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8005"
    networks:
      - app_network
    ports:
      - 8005:8005

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: Frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
  redis_data: