"""init_migrations

Revision ID: 7459e6498965
Revises: 
Create Date: 2025-03-03 18:32:23.376823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7459e6498965'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DEFAULT', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('connection',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('OWNER', 'CO_CREATOR', 'DEFAULT', name='connectiontype'), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('email', 'id_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection')
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
